name: docker_image_advance_puhsing

on:
  push:
    branches:
      - main

jobs:
  docker_image_puhsing:
    runs-on: ubuntu-latest
    steps:
      - name: checkingout_repo
        uses: actions/checkout@v4

      - name: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOKCER_ACCESS_TOKEN}}

      - name: build_and_publish
        id: xyz
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/test_action:latest

      - name: digest
        run: echo ${{steps.xyz.outputs.digest}}
