name: docker_image_pushing

on:
  push:
    branches:
      - main

jobs:
  puhsing_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkingout_repo
        uses: actions/checkout@v3

      - name: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOKCER_ACCESS_TOKEN}}
