name: dokcer_puhsing_metadata_artifacts

on:
  push:
    branches:
      - main

jobs:
  docker_push_with_metadata_arrtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: checking_out_repo
        run: |
          echo ${{ github.repository }}
