name: dokcer_puhsing_metadata_artifacts

on:
  push:
    branches:
      - main

jobs:
  docker_push_with_metadata_arrtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: checking_out_repo
        uses: actions/checkout@v3

      - name: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOKCER_ACCESS_TOKEN}}

      - name: extract_metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{secrets.DOCKER_USERNAME}}/test_action:latest

      - name: build_and_publish
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}

      - name: generate_artifacts_attestion
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{secrets.DOCKER_USERNAME}}/test_actisson:latest
          subject-digest: ${{steps.push.outputs.digest}}
          push-to-registry: true
