name: docker_image_pushing

on:
  push:
    branches:
      - main

jobs:
  puhsing_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkingout_repo
        uses: actions/checkout@v3

      - name: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOKCER_ACCESS_TOKEN}}

      - name: build_and_publish_dockerimage
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/test_action:latest
      - name: image_digest
        run: echo ${{ steps.puhsing_docker_image.outputs.digest}}
