name: greet_on_txt

on:
  push:
    branches:
      - main
    paths:
      - "**.txt"

jobs:
  greet_on_txt:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "Hello Kutte"
