name: on_pull_request_test

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  on_specfic_commit:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo ${{ github.actor }}
