name: on_specfic_user_commit

on:
  push:
    branches:
      - main

jobs:
  on_specifc_user_commit:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.actor == 'gftmadan'}}
        run: echo "Welcome GFTMADAN !!!!"

      - if: ${{ github.actor == 'UtkShowcase'}}
        run: echo "Welcome UTKSHOWCASE"
