name: running_both_repo_scripts

on:
  push:
    branches:
      - main

jobs:
  running_both_repo_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_from_current_reop
        uses: actions/checkout@v3

      - name: checkout_from_gftmadan_repo
        uses: actions/checkout@v3
        with:
          repository: gftmadan/test1
          token: ${{secrets.MY_REPO_PAT}}

      - name: setuping_python
        uses: actions/setup-python@v4

      - name: running scipts
        run: |
          dir
          python main.py
          python test.py
