name: using_container_with_job

on:
  push:
    branches:
      - main

jobs:
  using_container_with_job:
    runs-on: ubuntu-latest
    container:
      image: gftmadan/githubaction
    steps:
      - name: checking_out_repo
        uses: actions/checkout@v3

      - name: running_a1_python_script
        run: python a1.py
